{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- include "common.pvc" (dict "name" (printf "%s-data" (include "common.fullname" .)) "spec" .Values.persistence "root" $) }}
{{- end }}
