default_language_version:
  python: python3
  node: "24.6.0"

repos:
  - repo: local
    hooks:
      # Enforces formatting during commit
      - id: prettier
        name: prettier (check)
        entry: prettier --ignore-unknown --check
        language: node
        types: [file]
        additional_dependencies:
          - prettier@3.6.2

      # Optional: run manually to fix formatting
      - id: prettier-fix
        name: prettier (fix)
        entry: prettier --ignore-unknown --write
        language: node
        types: [file]
        stages: [manual]
        additional_dependencies:
          - prettier@3.6.2

      - id: ct-lint
        name: chart-testing lint
        entry: ct lint --config ct.yaml
        language: system
        pass_filenames: false
        files: ^charts/
        stages: [pre-commit]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["--fix"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: "\\.(ya?ml)$"

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        # add args as you like, e.g.:
        # args: ["--chart-search-root=."]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: ^\.github/workflows/.*\.ya?ml$
