{{- range $ad := .Values.l2Advertisements | default list }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $ad.name | required "l2Advertisements[].name is required" | trunc 63 | trimSuffix "-" }}
spec:
  {{- with $ad.ipAddressPools }}
  ipAddressPools:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
---
{{- end }}
