{{- if .Values.primary.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "common.metadata" (dict "name" (printf "%s-config" (include "common.fullname" .)) "root" $) | nindent 2 }}
data:
  my.cnf: |
    {{- .Values.primary.configuration | nindent 4 }}
{{- end }}
