apiVersion: v1
kind: Service
metadata:
  {{- include "common.metadata" (dict "name" (include "common.fullname" .) "root" $) | nindent 2 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "common.selectorLabels" $ | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 9104
      targetPort: metrics
      protocol: TCP
    {{- end }}
