{{- if and .Values.civicrm.siteKey (not .Values.civicrm.existingSecretSiteKey) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "common.metadata" (dict "name" (printf "%s-sitekey" .Release.Name) "root" $) | nindent 2 }}
type: Opaque
stringData:
  site-key: {{ .Values.civicrm.siteKey | quote }}
{{- end }}
