apiVersion: v2
name: linkwarden
description: Linkwarden - self-hosted collaborative bookmark manager
type: application
version: 0.1.0
appVersion: v2.14.0
keywords:
  - linkwarden
  - bookmarks
  - bookmark-manager
  - self-hosted
home: https://linkwarden.app
sources:
  - https://github.com/linkwarden/linkwarden
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common
