apiVersion: v2
name: lazylibrarian
description: LazyLibrarian - Book, audiobook and magazine collection manager for Usenet and BitTorrent users
type: application
version: 0.1.0
appVersion: "6324496a"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
