apiVersion: v2
name: kavita
description: Kavita - Self-hosted digital library server for ebooks, comics and manga
type: application
version: 0.1.0
appVersion: "0.9.0"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
