apiVersion: v2
name: obsidian
description: Web-accessible Obsidian MD desktop client packaged by LinuxServer.io
home: https://github.com/linuxserver/docker-obsidian
keywords:
  - obsidian
  - notes
  - markdown
  - linuxserver
sources:
  - https://github.com/linuxserver/docker-obsidian
type: application
version: 0.1.0
appVersion: "1.5.3"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common
