# Common labels/annotations applied to all resources
commonLabels: {}
commonAnnotations: {}

# Override the name of the chart
nameOverride: ""

# Override the full name of the resources
fullnameOverride: ""

# Number of Obsidian replicas (stateful desktop app, keep at 1)
replicaCount: 1

# Container image configuration
image:
  repository: ghcr.io/linuxserver/obsidian
  tag: "1.5.3"
  pullPolicy: IfNotPresent

# Image pull secrets for private registries
imagePullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 3000
  additionalPorts:
    - name: websocket
      port: 3001
      targetPort: 3001
      protocol: TCP
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: obsidian.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Persistent storage for Obsidian configuration and vaults
persistence:
  config:
    enabled: true
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    existingClaim: ""

# Standard LinuxServer.io environment variables
linuxserver:
  puid: "1000"
  pgid: "1000"
  timezone: "UTC"
  umask: "022"
  subfolder: ""

# Additional environment configuration
extraEnv: []
extraEnvFrom: []

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Resource requests and limits
resources: {}

# Node selector for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity for pod assignment
affinity: {}
