{{- range $i, $issuer := .Values.instances }}
{{- if and $issuer.cloudflare.sealedSecret.create (.Capabilities.APIVersions.Has "bitnami.com/v1alpha1/SealedSecret") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $issuer.cloudflare.secret.name | required "cloudflare.secret.name is required" }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
    {{- toYaml $issuer.cloudflare.sealedSecret.encryptedData | nindent 4 }}
{{- else if $issuer.cloudflare.sealedSecret.create }}
{{- fail "SealedSecrets CRD not found; install it or disable cloudflare.sealedSecret.create" }}
{{- end }}
{{- end }}
