{{- range $i, $issuer := .Values.instances }}
  {{- with $issuer.cloudflare.secret }}
    {{- if .create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required (printf "instances[%d].cloudflare.secret.name is required" $i) .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- toYaml .stringData | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
