{{- if and .Values.postiz.persistence.config.enabled (not .Values.postiz.persistence.config.existingClaim) }}
{{- include "common.pvc" (dict "name" (printf "%s-config" (include "common.fullname" .)) "spec" .Values.postiz.persistence.config "root" $) }}
{{- end }}
